[phases.setup]
nixPkgs = ["nodejs_18", "yarn", "caddy"]

[phases.install]
cmds = ["yarn install"]

[phases.build]
cmds = ["yarn build"]

[start]
cmd = "caddy run --config Caddyfile --adapter caddyfile"
