[build]
  base = "frontend"
  command = "npm install --legacy-peer-deps && NODE_OPTIONS=--openssl-legacy-provider npm run build"
  publish = "build"

[build.environment]
  CI = "false"
  REACT_APP_BACKEND_URL = "https://bruno-melito-hair-production.up.railway.app"
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
